#!/usr/bin/env node
/**
 * generate-skill.js
 * Auto-generates SKILL.md from README.md + docs/en/ content.
 * Runs automatically via GitHub Actions on every push to main.
 */

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');

// ── helpers ──────────────────────────────────────────────────────────────────

function read(filePath) {
  const full = path.join(ROOT, filePath);
  return fs.existsSync(full) ? fs.readFileSync(full, 'utf8') : '';
}

/** Extract a section by heading from a markdown string */
function extractSection(md, heading) {
  const regex = new RegExp(
    `#+\\s*${heading.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}[\\s\\S]*?(?=\n#+\\s|$)`,
    'i'
  );
  const match = md.match(regex);
  return match ? match[0].trim() : '';
}

/** Strip YAML frontmatter if present */
function stripFrontmatter(md) {
  return md.replace(/^---[\s\S]*?---\n?/, '').trim();
}

/** Extract package.json description */
function getPackageDescription() {
  try {
    const pkg = JSON.parse(read('package.json'));
    return pkg.description || '';
  } catch {
    return '';
  }
}

// ── build content ────────────────────────────────────────────────────────────

const readme     = stripFrontmatter(read('README.md'));
const quickstart = stripFrontmatter(read('docs/en/QUICKSTART.md'));
const skills_ref = stripFrontmatter(read('docs/en/SKILLS_REFERENCE.md'));

// Pull key sections from README
const overview    = extractSection(readme, 'Overview');
const categories  = extractSection(readme, 'Skill Categories');
const philosophy  = extractSection(readme, 'Design Philosophy');
const implementation = extractSection(readme, 'Implementation');
const status      = extractSection(readme, 'Project Status');

// Pull best-practices + workflows from QUICKSTART
const bestPractices = extractSection(quickstart, 'Best Practices');
const workflows     = extractSection(quickstart, 'Common Workflows');
const cheatSheet    = extractSection(quickstart, 'Skill Cheat Sheet');

// ── frontmatter ──────────────────────────────────────────────────────────────

const pkgDesc = getPackageDescription();

const description = pkgDesc ||
  'Advanced AI agent skill system with modular capabilities for autonomous programming. ' +
  'Includes file operations, code understanding, semantic search, terminal execution, ' +
  'testing, refactoring, version control, project management, memory/context management, ' +
  'and AI-specific skills. Use when you need a comprehensive framework for autonomous ' +
  'software development tasks.';

const frontmatter = `---
name: manus-skills
description: ${description}
license: MIT
metadata:
  author: antonygiomarxdev
  version: "1.0.0"
  tags: ai, agent, typescript, autonomous, programming, skills
  generated: "${new Date().toISOString().split('T')[0]}"
---`;

// ── assemble SKILL.md ────────────────────────────────────────────────────────

const body = [
  '> ⚙️ *This file is auto-generated by `scripts/generate-skill.js` — do not edit manually.*',
  '',
  overview,
  categories,
  workflows     ? `## Common Workflows\n\n${workflows.replace(/^#+\s*Common Workflows\s*/i, '').trim()}` : '',
  cheatSheet    ? `## Skill Cheat Sheet\n\n${cheatSheet.replace(/^#+\s*Skill Cheat Sheet\s*/i, '').trim()}` : '',
  bestPractices ? `## Best Practices\n\n${bestPractices.replace(/^#+\s*Best Practices\s*/i, '').trim()}` : '',
  philosophy,
  implementation,
  status,
]
  .filter(Boolean)
  .join('\n\n');

const output = `${frontmatter}\n\n${body}\n`;

// ── write ────────────────────────────────────────────────────────────────────

const outPath = path.join(ROOT, 'SKILL.md');
fs.writeFileSync(outPath, output, 'utf8');
console.log(`✅ SKILL.md generated (${output.length} chars)`);
